export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCEEDED = 'FETCH_ALL_USERS_SUCCEEDED';
export const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';

export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_USER_INFO_SUCCEEDED = 'FETCH_USER_INFO_SUCCEEDED';
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED';

export const DELETE_USER_BY_ID = 'DELETE_USER_BY_ID';
export const DELETE_USER_BY_ID_SUCCEEDED = 'DELETE_USER_BY_ID_SUCCEEDED';
export const DELETE_USER_BY_ID_FAILED = 'DELETE_USER_BY_ID_FAILED';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
export const UPDATE_USER_INFO_SUCCEEDED = 'UPDATE_USER_INFO_SUCCEEDED';
export const UPDATE_USER_INFO_FAILED = 'UPDATE_USER_INFO_FAILED';


export const CREATE_USER_INFO = 'CREATE_USER_INFO';
export const CREATE_USER_INFO_SUCCEEDED = 'CREATE_USER_INFO_SUCCEEDED';
export const CREATE_USER_INFO_FAILED = 'CREATE_USER_INFO_FAILED';
