export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ALL_USERS_SUCCEEDED = 'FETCH_ALL_USERS_SUCCEEDED';
export const FETCH_ALL_USERS_FAILED = 'FETCH_ALL_USERS_FAILED';

export const FETCH_USER_INFO = 'FETCH_USER_INFO'; 
export const FETCH_USER_INFO_SUCCEEDED = 'FETCH_USER_INFO_SUCCEEDED'; 
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED'; 
